
# parsetab.py
# This file is automatically generated. Do not edit.
_tabversion = '3.2'

_lr_method = 'LALR'

_lr_signature = '\xbb\xa5\xaaCw_\xb3\xad\x9a\xaaJ\x12\xf3\xe0P\xb2'
    
_lr_action_items = {'CONSTANT':([0,6,8,9,10,12,15,],[2,2,2,-3,2,-4,2,]),'STRING':([0,6,8,9,10,12,15,],[3,3,3,-3,3,-4,3,]),'NUMBER':([0,6,8,9,10,12,15,],[4,4,4,-3,4,-4,4,]),'IMP':([1,2,3,4,7,16,],[8,-7,-6,-5,-8,-9,]),'COMMA':([2,3,4,7,13,16,],[-7,-6,-5,-8,15,-9,]),'LPAREN':([2,],[10,]),'VARIABLE':([0,6,8,9,10,12,15,],[7,7,7,-3,7,-4,7,]),'RPAREN':([2,3,4,7,13,14,16,17,],[-7,-6,-5,-8,-10,16,-9,-11,]),'DOT':([1,2,3,4,7,16,],[9,-7,-6,-5,-8,-9,]),'$end':([5,6,9,11,12,],[0,-1,-3,-2,-4,]),}

_lr_action = { }
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = { }
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'args':([10,15,],[14,17,]),'term':([0,6,8,10,15,],[1,1,1,13,13,]),'program':([0,6,],[5,11,]),'statement':([0,6,8,],[6,6,12,]),}

_lr_goto = { }
for _k, _v in _lr_goto_items.items():
   for _x,_y in zip(_v[0],_v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = { }
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> program","S'",1,None,None,None),
  ('program -> statement','program',1,'p_simple_program','st.py',141),
  ('program -> statement program','program',2,'p_complex_program','st.py',145),
  ('statement -> term DOT','statement',2,'p_simple_statement','st.py',150),
  ('statement -> term IMP statement','statement',3,'p_complex_statement','st.py',154),
  ('term -> NUMBER','term',1,'p_atomic_term','st.py',158),
  ('term -> STRING','term',1,'p_atomic_term','st.py',159),
  ('term -> CONSTANT','term',1,'p_atomic_term','st.py',160),
  ('term -> VARIABLE','term',1,'p_atomic_term','st.py',161),
  ('term -> CONSTANT LPAREN args RPAREN','term',4,'p_function_term','st.py',165),
  ('args -> term','args',1,'p_atomic_arg','st.py',169),
  ('args -> term COMMA args','args',3,'p_complex_arg','st.py',173),
]
